export const DESKTOP_RPC_CHANNELS = [
  'errorSources:getAll',
  'errorSources:getOne',
  'errorSources:create',
  'errorSources:update',
  'errorSources:delete',
  'errorSources:initiateOAuth',
  'errorSources:completeOAuth',
  'errorSources:testConnection',
  'errorSources:probeConnection',
  'errorSources:triggerSync',
  'errorIssues:list',
  'errorEvents:list',
  'errorEvents:getOne',
  'settings:getAll',
  'settings:getGeneral',
  'settings:updateGeneral',
  'settings:getSecurity',
  'settings:updateSecurity',
  'settings:getNotifications',
  'settings:updateNotifications',
  'globals:list',
  'globals:create',
  'globals:update',
  'globals:delete',
  'settings:getAlertRules',
  'settings:createAlertRule',
  'settings:updateAlertRule',
  'settings:deleteAlertRule',
  'settings:initializeDefaults',
  'dialog:showSaveDialog',
  'dialog:showOpenDialog',
  'agent:start',
  'agent:send',
  'agent:cancel',
  'agent:getStatus',
  'agent:getSnapshot',
  'runbooks:list',
  'runbooks:get',
  'runbooks:create',
  'runbooks:updateMeta',
  'runbooks:updateActions',
  'runbooks:saveAction',
  'runbooks:deleteAction',
  'runbooks:reorderActions',
  'runbooks:delete',
  'runbooks:exportContext',
  'runbooks:export',
  'runbooks:exportToFile',
  'runbooks:import',
  'runbooks:readImportArtifact',
  'runbooks:importFromFile',
  'runbooks:execute',
  'runbooks:getExecution',
  'runbooks:cancelExecution',
  'incidents:getState',
  'incidents:replaceState',
  'desktopState:bootstrap',
  'desktopState:syncIncidents',
  'desktopState:syncRunbooks',
  'desktopState:syncResults',
] as const;

export type DesktopRpcChannel = (typeof DESKTOP_RPC_CHANNELS)[number];

export const DESKTOP_RPC_CHANNEL_SET = new Set<string>(DESKTOP_RPC_CHANNELS);

export const desktopChannelToTrpcPath = (channel: DesktopRpcChannel): string =>
  channel;
